version: '3.9'
services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - $MS_PORT:8080
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

